Kanaries/pygwalker

pygwalker/__init__.py, pygwalker/gwalker.py
As proposed here https://github.com/Kanaries/pygwalker/issues/24
=> [Feat]: Added to_html API to pygwalker

pygwalker/templates/walk.js, pyproject.toml
Might fix issues #17 and #27 .
=> [Fix]: JSON.parse errors when DataFrame contains special characters

pygwalker/gwalker.py, pygwalker/templates/walk.js, pygwalker/utils/gwalker_props.py
=> Revert "[Feat]: Dump dataSource in tight mode to reduce .ipynb file size."

README.md
+ fix slack link
+ add package downloads badage
=> fix: slack link

.github/workflows/auto-ci.yml, README.md, app/package.json, app/src/components/options.tsx, app/src/index.tsx, app/src/interfaces/index.ts, app/yarn.lock, pygwalker/__init__.py, pygwalker/__main__.py, pygwalker/__version__.py, pygwalker/base.py, pygwalker/utils/check_update.py, pygwalker/utils/config.py, pygwalker/utils/defaults.json, pygwalker/utils/render.py, pyproject.toml, tests/offline.ipynb
- user-wide configuration either through the command line or through Python API
```
% pygwalker config --set
usage: pygwalker config [--set [key=value ...]] | [--reset [key ...]].
Available configurations:
- privacy        ['offline', 'get-only', 'meta', 'any'] (default: meta).
"offline"   : no data will be transferred other than between the front-end and back-end of the notebook.
"get-only"  : the data will not be uploaded but only fetched from external servers.
"meta"      : only the desensitized data will be processed by external servers. There might be some server-side processing tasks performed on the metadata in future versions.
"any"       : the data can be processed by external services.
```
=> [Feat] Support configuring user-wide privacy policy

pygwalker/utils/gwalker_props.py
This is a squashed version of #129. Closes #129.
=> Added modin.🐼 suppport.

app/src/index.tsx
=> fix: fix to_html bug

app/package.json, app/src/components/codeExportModal/index.tsx, app/yarn.lock, pygwalker/api/html.py, pygwalker/api/walker.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/modin_parser.py, pygwalker/data_parsers/pandas_parser.py, pygwalker/data_parsers/polars_parser.py, pygwalker/services/data_parsers.py, pygwalker/services/fname_encodings.py, pygwalker/services/format_invoke_walk_code.py
=> Feat: add custom data parser 

app/package.json, app/src/components/codeExportModal/index.tsx, app/src/components/options.tsx, app/src/dataSource/index.ts, app/src/index.tsx, app/src/interfaces/index.ts, app/yarn.lock
fix some types, lint, code style (prettier);
but there are still lots of code need refactor...
=> fix: types & lint issues

README.md
Removed "ability to" text which was twice. Making readme.md file more concise.
=> #145 Update README.md

app/src/index.tsx, app/src/interfaces/index.ts, app/src/tools/saveTool.tsx, pygwalker/__init__.py, pygwalker/api/html.py, pygwalker/api/pygwalker.py, pygwalker/api/walker.py, pygwalker/services/spec.py, pygwalker/services/tip_tools.py, pygwalker/utils/execute_env_check.py
[add store_chart_data param](https://github.com/Kanaries/pygwalker/commit/1a3cb0a450f98a49ec2763d9c6e6aeb08adaef38)
[add NbConvert adapter](https://github.com/Kanaries/pygwalker/commit/ca6a778a562357ca9bd06bc908dabb8e21f45ac1)
=> chore: bump to v0.2.0a4

pygwalker/__init__.py, pygwalker/services/calculation.py
1. [fix: fix polars bug in use_kernel_calc](https://github.com/Kanaries/pygwalker/commit/9cdcde9f985f4e898f8d01d22860a526c517bfe4)
=> chore: bump to v0.3.1

app/src/index.tsx, app/src/interfaces/index.ts, app/src/utils/communication.ts, pygwalker/api/html.py, pygwalker/api/pygwalker.py, pygwalker/api/streamlit.py, pygwalker/api/walker.py
update renderer mode of grahpic-walker(without filter).
link issue: #257
=> feat: streamlit support renderer mode of graphic-walker

app/package.json, app/yarn.lock
=> feat: update grpahic-walker to support fold feature

pygwalker/api/streamlit.py, pygwalker/communications/streamlit_comm.py
add pre_filter param in streamlit, This allows users to use other components to complete filtering data of pygwalker.
=> feat: streamlit add pre-filters feature

pygwalker/api/streamlit.py, pygwalker/utils/encode.py
convert datetime to number for millisecond timestamp, to fix date range bugs.
=> feat: convert datetime to number for millisecond timestamp

app/src/index.tsx, app/src/interfaces/index.ts, pygwalker/__init__.py, pygwalker/api/pygwalker.py
Temporarily update the gpt feature of graphic-walker: text to chart.
=> feat: add vizgpt feature(temporary)

app/src/utils/communication.tsx, pygwalker/api/pygwalker.py, pygwalker/api/walker.py, pygwalker/communications/base.py, pygwalker/communications/streamlit_comm.py, pygwalker/errors.py, pygwalker/services/cloud_service.py
Added some friendly tips when using cloud functions.
=> feat: modify cloud server tips

pygwalker/api/pygwalker.py, pygwalker/api/streamlit.py, pygwalker/api/walker.py, pygwalker/utils/display.py
Extract some streamlit code  in PygWalker class to single streamlit module.
=> refactor: streamlit module

pygwalker/api/kanaries_cloud.py, pygwalker/services/cloud_service.py
Previous, `create_cloud_graphic_walker` included both creation and acquisition functions.
This may feel strange to the user, Now put these functions into different methods.
=> refacotr: split fucntion from create_cloud_graphic_walker

app/package.json, app/src/index.tsx, app/src/interfaces/index.ts, app/src/tools/saveTool.tsx, app/yarn.lock, pygwalker/__init__.py, pygwalker/api/pygwalker.py
update graphic-walker to 0.4.25.
remove hack functions about `storeRef.current.commonStore`.
=> feat: update graphic-walker to 0.4.25

app/package.json, app/src/dataSource/index.ts, app/src/index.tsx, app/src/interfaces/index.ts, app/yarn.lock, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/database_parser.py, pygwalker/data_parsers/modin_parser.py, pygwalker/data_parsers/spark_parser.py, pyproject.toml
This PR fix some errors when converting timestamp fields to sql.
But, There are still some problems when converting temporal type fields to sql. We may spend some time optimizing it.
=> fix: fix timestamp field to sql bugs

app/src/components/codeExportModal/index.tsx, app/src/components/codeExportModal/usePythonCode.ts, app/src/components/shareModal/index.tsx, app/src/index.tsx
Fixed components that were not updated in time due to updating graphic-walker.
=> fix: modify IGlobalStore to VizSpecStore

app/package.json, app/yarn.lock, pygwalker/services/cloud_service.py, pygwalker/utils/encode.py, pyproject.toml
Modify some errors in filter expressions when converting dsl to sql.
=> fix: filter bugs in connector and duckdb && add chart exists tips when create shared chart

app/package.json, app/src/index.tsx, app/src/store/common.ts, app/yarn.lock, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/services/cloud_service.py
The requester of the ask-viz feature api has been changed from the frontend to the python side, avoids the risk of kanaries_token leakage.
And, add tips when request ask-viz fail.
=> feat: modify request way of ask-viz api

app/src/index.tsx, app/src/utils/save.ts, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/api/streamlit.py
* Fixed the parameter bug of PureRenderer component when upgrading graphic-walker
* Fixed save error when table chart dom is null
=> fix: pure renderer params bugs in streamlit

.github/workflows/auto-ci.yml, app/package.json, app/src/dataSource/index.ts, app/src/tools/exportDataframe.tsx, app/yarn.lock, pygwalker/api/pygwalker.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/database_parser.py, pygwalker/data_parsers/modin_parser.py, pygwalker/data_parsers/pandas_parser.py, pygwalker/data_parsers/polars_parser.py, pygwalker/data_parsers/spark_parser.py, pygwalker/utils/encode.py, pyproject.toml
In the past, there were some time zone problems when using time range, time drill, and time feature. Currently, pygwalker will align the time with your local time zone.
=> fix: temproal timezone bugs

pygwalker/__init__.py, pygwalker/api/walker.py, pygwalker/services/kaggle.py
Added some tips for using Pygwalker on Kaggle to enhance the user experience.
=> feat: add kaggle tips

app/package.json, app/src/components/codeExportModal/index.tsx, app/src/components/codeExportModal/usePythonCode.ts, app/src/index.tsx, app/src/interfaces/index.ts, app/src/tools/saveTool.tsx, app/yarn.lock, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/api/streamlit.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/polars_parser.py, pygwalker/services/fname_encodings.py, pygwalker/services/spec.py
1. Fixed some bugs caused by the removal of fid encoding. 
2. Readjusted the format of the config string.
=> fix: fix bugs of removing fid encode

app/src/components/uploadChartModal/index.tsx, app/src/index.tsx, app/src/tools/uploadChartTool.tsx, pygwalker/__init__.py, pygwalker/api/kanaries_cloud.py, pygwalker/api/pygwalker.py, pygwalker/services/cloud_service.py
This time, we are releasing an experimental feature to further improve the user experience of publishing pygwalker charts on kanaries cloud.
=> feat: add upload chart to cloud

app/package.json, app/yarn.lock, pygwalker/__init__.py
refer it: https://github.com/Kanaries/graphic-walker/pull/273
=> feat: auto add filter field when data painter saved

app/package.json, app/src/index.tsx, app/yarn.lock, pygwalker/__init__.py, pyproject.toml
refer it: [How to Create Computed field in Graphic Walker
](https://github.com/Kanaries/graphic-walker/wiki/How-to-Create-Computed-field-in-Graphic-Walker)
=> feat: add calculation field

app/package.json, app/yarn.lock, pygwalker/__init__.py
upgrade graphic-walker to support data-painter with nominal field
=> release: 0.4.1

app/package.json, app/src/components/codeExportModal/usePythonCode.ts, app/src/dataSource/index.ts, app/src/tools/exportDataframe.tsx, app/src/tools/saveTool.tsx, app/yarn.lock, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/cloud_dataset_parser.py, pygwalker/data_parsers/database_parser.py, pygwalker/data_parsers/spark_parser.py, pygwalker_tools/metrics/api.py, pyproject.toml
This PR solves the problem that user can't select the time zone when using time-related features.
related issue: https://github.com/Kanaries/pygwalker/issues/395
new feature details: https://github.com/Kanaries/graphic-walker/pull/297
=> feat: use new time offset config

pygwalker/__init__.py, pygwalker/api/streamlit.py
set show_cloud_tool param default value in streamlit
=> chore: bump to v0.4.4

app/src/dataSource/index.ts, pygwalker/api/gradio.py, pygwalker/api/html.py, pygwalker/api/pygwalker.py, pygwalker/api/streamlit.py, pygwalker/api/walker.py, pygwalker/services/cloud_service.py
When users analyze big data dataframes, local computing resources may not support users' data exploration. Pygwalker provides cloud computing resources. Users only need to change one parameter to upload the data to kanaries cloud and use the computing resources of kanaries cloud to explore datas.
example:
```python
import pygwalker as pyg
pyg.walk(df, use_cloud_calc=True)
```
=> feat: cloud calculate

app/src/components/uploadChartModal/index.tsx, pygwalker/api/pygwalker.py, pygwalker/services/cloud_service.py
Allow users to upload pygwalker's charts to kanaries cloud more flexibly.
=> feat: update feature for uploading chart to cloud

app/src/index.tsx, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/services/cloud_service.py
=> feat: support chat feature

app/src/index.tsx, app/src/tools/saveTool.tsx, pygwalker/__init__.py
=> feat: add red point when spec changed

pygwalker/__init__.py, pyproject.toml
related issue: https://github.com/Kanaries/pygwalker/issues/516
=> chore: update duckdb version

pygwalker/communications/base.py, pygwalker/communications/gradio_comm.py, pygwalker/communications/hacker_comm.py, pygwalker/communications/streamlit_comm.py
pygwalker will collect error logs to improve the iteration of the feature.
Privacy details reference: https://github.com/Kanaries/pygwalker?tab=readme-ov-file#configuration-and-privacy-policypygwlaker--0310
=> feat: collect error log

app/package.json, app/src/index.tsx, app/src/store/common.ts, app/src/utils/communication.tsx, app/yarn.lock, pygwalker/__init__.py, pygwalker/api/streamlit.py, pygwalker/services/preview_image.py, pygwalker/services/render.py, pygwalker/services/streamlit_components.py, pygwalker/templates/index.html, pygwalker/templates/pygwalker_main_page.html
In streamlit, pygwalker support render pygwalker html by streamlit custom component.
And supports return spec when spec changes.
example:
```python
from pygwalker.api.streamlit import StreamlitRenderer
import streamlit as st
@st.cache_resource
def get_pyg_renderer() -> "StreamlitRenderer":
df = pd.read_csv("xxx")
return StreamlitRenderer(df)
renderer = get_pyg_renderer()
event = renderer.explorer()
print(event)
```
=> feat: support streamlit custom component

pygwalker/__init__.py, pygwalker/api/streamlit.py, pygwalker/services/data_parsers.py
related issue: https://github.com/Kanaries/pygwalker/issues/604
=> fix: rendering in streamlit

app/src/index.tsx
remove the duplicate "gw_dsl_parser_bg.wasm" in result package "pygwalker_iife.js".
=> fix: remove duplicate dsl parser

app/package.json, app/src/components/preview/index.tsx, app/yarn.lock, pygwalker/services/preview_image.py, pygwalker/services/render.py, pygwalker/templates/pygwalker_main_page.html
compress all data in html, to reduce the size of html.
=> feat: compress all data in html

pygwalker/data_parsers/database_parser.py
related issue: https://github.com/Kanaries/pygwalker/issues/629
=> fix: exp.Subquery alias

scripts/test-init.sh
The code file needed few changes, i made a new branch and updated the code file there. 
#622 Resolved the issue.
=> chore: update test-init.sh

pygwalker/data_parsers/database_parser.py
related issue: https://github.com/Kanaries/pygwalker/issues/629
=> fix: mssql dialect map

pygwalker/__init__.py, pygwalker/api/marimo.py
related issue: https://github.com/Kanaries/pygwalker/issues/638
=> fix: marimo component encoding

README.md, docs/README.de.md, docs/README.es.md, docs/README.fr.md, docs/README.ja.md, docs/README.ko.md, docs/README.tr.md, docs/README.zh.md
=> README spelling correction

app/src/index.tsx, app/src/tools/openDesktop.tsx, pygwalker/__init__.py, pygwalker/api/pygwalker.py
add a button in toolbar, to open the chart in graphic walker desktop.
=> feat: open in desktop

CITATION.cff, CONDUCT.md, README.md, bin/pygwalker_command.py, pygwalker/services/check_update.py
As a student studying Research Software Engineering (RSE) and Software Quality (SQ) courses at Uni-Potsdam, I'm excited to contribute to this project. This Pull Request aims to enhance code readability by aligning with Python code review checklists and PEP8 style guidelines. Additionally, it seeks to improve the project's FAIR4RS score.
=> Improve: Code readability, python linter score, FAIR4RS score
