pygwalker/gwalker.py
`pd.DataFrame.to_dict` keeps NaN values as `float('nan')` and `json.dumps`  handles the transformation of numbers directly instead of delegating to a `json.JSONEncoder` class. Then the json output contains 'nan' which cannot be handled by javascript's `JSON.parse`.
Our solution is replacing NaN's in DataFrames with `None`, which leads to a standard `'null'` in json.
=> [Fix]:issue of parsing nan

pygwalker/base.py
Fixes Windows + JupyterLab combination.
Without this fix, `pyg.walk(df)` throws: `'charmap' codec can't decode byte 0x8d in position 511737: character maps to <undefined>`
=> [windows]Open templates in utf8 encoding

pygwalker/utils/render.py
I did have some issues with Python objects which were previously not serializable with the current `DataFrameEncoder`. 
This PR allows all objects serializable to a String to be encoded to JSON, including the previous special cases for `datetime`.
=> [Feat]: Allows to serialize all Python classes with __str__ method

pygwalker/utils/gwalker_props.py
issue#125：
user can not load more data in stream because the limit in jupyter equally valid in streamlit env, but streamlit environments are not limited by ipynb.
The jupyter environment can be directly distinguished by the parameters.
=> fix: remove data restrictions for non-Jupyter env

pygwalker/__init__.py, pyproject.toml
temporarily limit duckdb version to fix datetime bug, after it, dsl-parser will be updated to adapt to the new version of duckdb.
=> chore: bump to v0.3.9

app/src/index.tsx, app/src/interfaces/index.ts, app/src/utils/communication.tsx, pygwalker/__init__.py, pygwalker/api/gradio.py, pygwalker/api/pygwalker.py, pygwalker/communications/gradio_comm.py, pygwalker/communications/streamlit_comm.py
support pygwalker use duckdb in gradio.
Just a pre-release demo version, Communication won't work when gradio is reloaded (to be fixed).
```python
import gradio as gr
from pygwalker.api.gradio import PYGWALKER_ROUTE, get_html_on_gradio
with gr.Blocks() as demo:
df = pd.read_csv("/Users/douding/Desktop/datas/hour.csv")
pyg_html = get_html_on_gradio(df, spec="gradio.json", debug=True)
gr.HTML(pyg_html)
app = demo.launch(app_kwargs={
"routes": [PYGWALKER_ROUTE]
})
```
=> feat: add communication on gradio(pre-demo)

pygwalker/__init__.py, pygwalker/api/streamlit.py
fix api: `get_streamlit_html`
expect:
run code,
```python
from pygwalker.api.streamlit import get_streamlit_html
df = pd.Dataframe()
html = get_streamlit_html(df)
```
return html string.
=> fix: streamlit api - get_streamlit_html

app/src/tools/saveTool.tsx
Previously, if user's spec was not a writable json file, a tips of using cloud file would pop up.
This is very unfriendly to users whose privacy is offline.
This PR is to improve it.
=> feat: hide cloud tips when privacy is offline

app/src/dataSource/index.ts, app/src/index.tsx, app/src/interfaces/index.ts, app/src/notify/index.tsx, app/src/tools/exportDataframe.tsx, pygwalker/api/gradio.py, pygwalker/api/html.py, pygwalker/api/kanaries_cloud.py, pygwalker/api/pygwalker.py, pygwalker/api/streamlit.py, pygwalker/api/walker.py, pygwalker/services/global_var.py, pygwalker/services/spec.py, pyproject.toml
Users can export the current chart data into a dataframe of pandas in jupyter notebook. This feature also prepares for the export various calculation measures provided by graphch-walker in the future.
=> feat: add export dataframe tool

pygwalker/data_parsers/database_parser.py, pygwalker/errors.py, tests/test_data_parsers.py
pygwalker won't work when users use connector and use incorrect `view_sql`, so pygwalker will check view_sql in advance and throw an exception in advance if it is incorrect.
=> feat: raise error when use incorrect view sql

pygwalker/__init__.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/modin_parser.py, pygwalker/data_parsers/pandas_parser.py, pygwalker/data_parsers/polars_parser.py, pygwalker/data_parsers/spark_parser.py, pygwalker/services/fname_encodings.py, pygwalker/services/spec.py, tests/test_data_parsers.py
Previously, pygwalker encoded fields to be compatible with the graphic-walker config format. This is no longer necessary, so we have removed the logic for double encoding fields.
This also makes it easier for us to provide computed fields in the future.
=> feat: remove encoding field name

pygwalker/__init__.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/cloud_dataset_parser.py, pygwalker/data_parsers/spark_parser.py, pygwalker_tools/metrics/__init__.py, pygwalker_tools/metrics/api.py, pygwalker_tools/metrics/core.py, pyproject.toml
We are trying to offer other tools, such as various metric templates, enabling users to explore the data metrics they require through setting field mapping.
for example: 
```python
from pygwalker_tools.metrics import MetricsChart
MetricsChart(
dataset,
{"date": "your_date_field", "user_id": "your_user_id_field", "user_signup_date": "your_user_signup_date_field"},
params={"time_unit": "day", "time_size": 7}
).retention()
```
=> feat: add metrics chart feature

bin/pygwalker_command.py, pygwalker/__init__.py, pygwalker/services/kanaries_cli_login.py
This feature is designed to make it easier for users to set their kanaries token locally.
With just one command, users can authorize on the web page to complete the token setting.
```bash
pygwalker login
```
=> feat: add login-cli to set kanaries token

pygwalker/api/html.py
`pyg.walk(df)` should focus on implementing relevant features in the jupyter.
`pyg.walk(df, return_html=True)`, it's confusing.
So we reuse `to_html` api.
```python
from pygwalker.api.html import to_html
to_html(df)
```
=> feat: recover to_html api

app/src/index.tsx, app/src/interfaces/index.ts, pygwalker/api/streamlit.py
1. use StreamlitRenderer(recommend)
```python
import streamlit as st
from pygwalker.api.streamlit import StreamlitRenderer
@st.cache_resource
def get_pyg_renderer() -> "StreamlitRenderer":
df = pd.read_csv("xxxx")
return StreamlitRenderer(df, spec="xxx")
renderer = get_pyg_renderer()
renderer.render_filter_renderer()
```
2. use get_streamlit_html
```python
from streamlit.components.v1 import html
from pygwalker.api.streamlit import get_streamlit_html
html(get_streamlit_html(pd.DataFrame(), mode="filter_renderer"), height=1000)
```
=> feat: streamlit add new component: filter renderer

app/package.json, app/src/index.tsx, app/yarn.lock, pygwalker/api/pygwalker.py, pygwalker/services/spec.py
When using the same spec and the same data, the results calculated using js and calculated using python kernel are inconsistent.
The reason is that the front-end time zone and the back-end time zone are inconsistent.
This PR changes the time zone during front-end calculation to utc, which is consistent with the kernel time zone.
=> fix: use utc timezone when using js calculate

app/package.json, app/src/lib/dslToWorkflow.ts, app/src/lib/vegaToDsl.ts, app/vite.config.ts, pygwalker/__init__.py, pygwalker/api/html.py, pygwalker/utils/dsl_transform.py, pygwalker_tools/metrics/api.py, pyproject.toml
**API Reference**
```python
def to_chart_html(
dataset: Union[DataFrame, Connector, str],
spec: Dict[str, Any],
*,
spec_type: Literal["graphic-walker", "vega"] = "graphic-walker",
theme_key: Literal['vega', 'g2'] = 'g2',
dark: Literal['media', 'light', 'dark'] = 'media',
) -> str:
"""
Generate HTML code of a chart by graphic-walker or vega spec.
Args:
- dataset (pl.DataFrame | pd.DataFrame | Connector, optional): dataset.
- spec (Dict[str, Any]): chart config data.
Kargs:
- spec_type (Literal["graphic-walker", "vega"]): type of spec.
- theme_key ('vega' | 'g2'): theme type.
- dark ('media' | 'light' | 'dark'): 'media': auto detect OS theme.
"""
pass
```
**Example**
```python
from pygwalker.api.html import to_chart_html
from IPython.display import display, HTML
html = to_chart_html(
df,
{ …
```
=> feat: add new api to_chart_html

pygwalker/api/gradio.py, pygwalker/api/streamlit.py, pygwalker/utils/check_walker_params.py
The previous 'debug' parameter was only used to restrict the ability to read and write spec files. We believe this parameter name is not meaningful, and we are replacing it with 'spec_io_mode.'
The 'spec_io_mode' parameter currently has two options: 'r' and 'wr,' where 'r' indicates that the spec is read-only, and 'wr' indicates that spec files can be saved.
previous:
```python
StreamlitRenderer(df, spec="./gw_config.json", debug=True)
```
current:
```python
StreamlitRenderer(df, spec="./gw_config.json", spec_io_mode="wr")
```
=> refactor: use spec_io_mode instead of debug parameter

pygwalker/api/html.py, pygwalker/api/pygwalker.py, pygwalker/services/render.py, pygwalker/templates/pygwalker_iframe.html
```python
def to_table_html(
df: DataFrame,
*,
theme_key: Literal['vega', 'g2'] = 'g2',
dark: Literal['media', 'light', 'dark'] = 'media',
**kwargs
) -> str:
"""
Generate embeddable HTML code of Graphic Walker with data of `df`.
Args:
- df (pl.DataFrame | pd.DataFrame, optional): dataframe.
Kargs:
- theme_key ('vega' | 'g2'): theme type.
- dark ('media' | 'light' | 'dark'): 'media': auto detect OS theme.
"""
pass
```
* example
```python
from pygwalker.api.html import to_table_html
with open("pyg_table.html", "w") as f:
f.write(to_table_html(df))
```
```python
def to_render_html(
df: DataFrame,
spec: str,
*,
theme_key: Literal['vega', 'g2'] = 'g2',
dark: Literal['media', 'light', 'dark'] = 'media',
**kwargs
) -> str:
"""
Args:
- df (pl.DataFrame | pd.DataFrame, optional): dataframe.
- spec …
```
=> feat: add new html apis

pygwalker/__init__.py, pygwalker/api/gradio.py, pygwalker/api/html.py, pygwalker/api/jupyter.py, pygwalker/api/kanaries_cloud.py, pygwalker/api/pygwalker.py, pygwalker/api/streamlit.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/cloud_dataset_parser.py, pygwalker/data_parsers/database_parser.py, pygwalker/data_parsers/modin_parser.py, pygwalker/data_parsers/spark_parser.py, pygwalker/services/data_parsers.py, tests/field-spec.ipynb
before:
```python
from pygwalker import FieldSpec
field_specs = {"season": FieldSpec("nominal", "dimension")}
pyg.walk(df, field_specs=field_specs)
```
currently:
```python
from pygwalker import FieldSpec
field_specs = [FieldSpec(fname="season", semantic_type="nominal", analytic_type="dimension")]
pyg.walk(df, field_specs=field_specs)
````
=> refactor: modify type of field_specs

app/src/index.tsx, app/src/utils/formatSpec.ts, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/services/spec.py
users can initialize graphic-walker through vega config.
```python
vega_sepc = {
"mark": "bar",
"encoding": {
"x": {"field": "season", "type": "nominal", "axis": {"labelAngle": 0}},
"y": {"field": "casual", "type": "quantitative", "aggregate": "sum"}
}
}
walker = pyg.walk(df, spec=vega_sepc)
```
=> feat: support vega spec

app/src/tools/saveTool.tsx, pygwalker/__init__.py
When the size mode of the chart is auto, python-end has no way to know the size of the chart that needs to be rendered.
```json
{
"size": {
"mode": "auto",
"width": 151,
"height": 548
}
}
```
When users click save icon, the real size of chart that will be written to the config.
=> fix: temporarily fix bugs of pure chart rendering in streamlit

app/package.json, app/src/components/codeExportModal/index.tsx, app/src/components/codeExportModal/usePythonCode.ts, app/src/components/preview/index.tsx, app/src/components/uploadChartModal/index.tsx, app/src/dataSource/index.ts, app/src/index.tsx, app/src/interfaces/index.ts, app/src/lib/dslToWorkflow.ts, app/src/lib/vegaToDsl.ts, app/src/tools/exportDataframe.tsx, app/src/tools/exportTool.tsx, app/src/tools/loginTool.tsx, app/src/tools/saveTool.tsx, app/src/tools/uploadChartTool.tsx, app/src/utils/formatSpec.ts, app/src/utils/save.ts, app/tsconfig.json, app/yarn.lock
This PR updates graphic walker to 0.4.56 to resolve issue about datetime apperence and background of downloaded image of charts.
=> fix: update graphic walker to 0.4.56

pygwalker/__init__.py, pygwalker/api/streamlit.py, pygwalker/services/spec.py, pyproject.toml
=> fix: StrictVersion was removed in python3.12

pygwalker/__init__.py, pygwalker/data_parsers/database_parser.py, pygwalker/utils/custom_sqlglot.py
=> fix: parse array field in mysql

app/src/index.tsx, pygwalker/api/streamlit.py
This is just a temporary solution.
Pygwalker is testing the component rendering method recommended by streamlit, which will not require users to specify additional width, height, and scrolling, about detail: https://github.com/Kanaries/pygwalker/issues/531
=> fix: viewer container size base on the root iframe in streamlit

app/package.json, app/yarn.lock, pygwalker/__init__.py
Starting from this version, some urgent bug fixes will be released with smaller version numbers.
For example, If you are using the "0.4.8" version, the "0.4.8.xxx" version update prompt will not appear in the UI.
Pre-release versions will be updated using another branch "pre-release".
=> feat: update graphic-walker version

pygwalker/services/format_invoke_walk_code.py
Use a simpler way to parse the source code that invoke `pygwalker.walk`.
Removed warning when parsing fails, because this will cause confusion to users, and it does not affect the use of pygwalker.
=> fix: parse source code in jupyter

app/src/components/codeExportModal/index.tsx
As I reported in this issue #542 , the `Copy to Clipboard` in the Code Export dislog causes a JavaScript error. 
The reason of this error was also mentioned in this issue and what I did is just to check the browser the user uses. For the Chromium based browser, just copy as the original way while for the Firefox and Webkit browser, directly calls the `navigator.clipboard.writeText` function.
=> fix: "Copy to Clipboard" in different browser

app/package.json, app/yarn.lock, pygwalker/__init__.py, pygwalker/data_parsers/database_parser.py, pygwalker/utils/custom_sqlglot.py, pyproject.toml
Update graphic-walker(0.4.64 -> 0.4.66).
Add iso time unit and adapt duckdb, mysql, postgres, snowflake.
Detail refer:
https://github.com/Kanaries/graphic-walker/releases/tag/0.4.65
https://github.com/Kanaries/graphic-walker/releases/tag/0.4.66
=> feat: add iso time unit

app/src/index.tsx, app/src/utils/communication.tsx, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/communications/streamlit_comm.py
When the user deploys pygwalker + streamlit on a customized proxy service, the pygwalker api url cannot be requested normally.
=> fix: wrong api url when deployment custom proxy server

app/src/index.tsx, app/src/tools/saveTool.tsx, pygwalker/api/pygwalker.py, pygwalker/services/preview_image.py, pyproject.toml
Optimize preview rendering process.
Rendering previews blocks the main thread, while saving functionality and app initialization rely on main thread resources. When the Jupyter server needs to communicate over the public internet (such as with Kaggle), rendering the preview app, which requires downloading a 9MB HTML file, can slow down other functions.
=> feat: modify render preview

pygwalker/__init__.py, pygwalker/communications/streamlit_comm.py, pygwalker/errors.py
In some special cases, it may not be possible to correctly inject pygwalker's route in tornado.
=> feat: add pygwalker web api tips in streamlit

examples/component_demo.ipynb, pygwalker/__init__.py, pygwalker/api/component.py, pygwalker/api/pygwalker.py, pyproject.toml, tests/test_component_api.ipynb
We're excited to announce an experimental new feature in pygwalker:
The component chaining API that enables intuitive, step-by-step chart construction. This feature currently supports rendering to static HTML.
Key Points:
* Introduces a chainable API for creating visualizations
* Allows for more intuitive and readable code
* Currently an experimental feature
* Limited to static HTML output at this time
Example usage:
```python
import pygwalker as pyg
df = pd.read_csv("xxx")
(
pyg.component(df)
.rect()
.encode(x='bin("feeling_temp", 6)', y='bin("temperature", 6)', color="MEAN(humidity)")
.layout(height=400, width=460)
)
```
For more examples, please refer to the `pygwalker/examples` directory in our repository.
Upcoming Improvements:
1. Optimize the size of pure chart …
=> feat: add component api

app/src/dataSource/index.tsx, pygwalker/__init__.py, pygwalker/api/pygwalker.py, pygwalker/errors.py, pygwalker/services/global_var.py
The current default number of returned data records is 50,000. Users can manually adjust this size using the limit tool in the UI interface.
=> feat: new tips for data limit

tests/test_data_parsers.py
**Kernel Spelling:**
There's a typo in `to_records_no_kernrl_result`. It should be `to_records_no_kernel_result` instead of `to_records_no_kernrl_result`. Fixing that will help avoid confusion when referencing that variable.
=> chore: updated a typo in test_data_parsers.py

pygwalker/api/pygwalker.py, pygwalker/data_parsers/base.py, pygwalker/data_parsers/cloud_dataset_parser.py, pygwalker/data_parsers/database_parser.py, pygwalker/data_parsers/modin_parser.py, pygwalker/data_parsers/pandas_parser.py, pygwalker/data_parsers/polars_parser.py, pygwalker/data_parsers/spark_parser.py, pygwalker/services/cloud_service.py
related pr: https://github.com/Kanaries/pygwalker/pull/634
=> chore: typo "dataset_tpye"

app/package.json, app/src/index.tsx, app/src/utils/communication.tsx, app/vite.config.ts, app/yarn.lock, pygwalker/__init__.py, pygwalker/api/marimo.py, pygwalker/communications/anywidget_comm.py, pyproject.toml
related issue:
https://github.com/Kanaries/pygwalker/issues/638
demo code:
```python
from pygwalker.api.marimo import walk
df = pd.read_csv("xxx.csv")
walk(df, spec="spec.json")
```
```python
import pygwalker.api.marimo as pyg
df = pd.read_csv("xxx.csv")
pyg.walk(df, spec="spec.json")
```
It can only make pygwalker work normally on Marimo, and currently no responsive features have been introduced.
=> feat: support marimo poc version

app/src/index.tsx, pygwalker/__init__.py, pygwalker/api/anywidget.py
support pure anywidget.
related issue: https://github.com/Kanaries/pygwalker/issues/650
example:
```python
from pygwalker.api.anywidget import walk
df = pd.read_csv("your_dataset_file.csv")
pyg_widget = walk(df)
```
panel example:
```python
from pygwalker.api.anywidget import walk
df = pd.read_csv("your_dataset_file.csv")
pyg_widget = walk(df)
pn.panel(pyg_widget, width=1500).servable()
```
=> feat: support common anywidget

README.md
Closes #650 .
When https://github.com/panel-extensions/panel-graphic-walker/pull/30 is merged there will be much more functionality.
=> Document panel-graphic-walker

README.md
This PR updates the English-language README with how to use Pygwalker in marimo.
Note that marimo patches `pygwalker.walk` to use `pygwalker.api.marimo.walk`, so `pygwalker.walk(df)` works in marimo. This was added in version 0.9.15 of marimo: https://github.com/marimo-team/marimo/pull/2798
=> docs: add marimo usage to README

examples/README.md, examples/marimo_demo.py
- Add marimo x Pygwalker demo code (reference to relevant issue comment - https://github.com/Kanaries/pygwalker/issues/638#issuecomment-2445667848)
- Add README for examples subfolder giving some context to running examples
I want to make some changes to the root README; including marimo in places where open in Google Colab and Kaggle links are provided. This will be a link to the marimo.cloud/marimo.new with a slug link; basically a marimo notebook running on the browser (made possible using [WASM ](https://marimo.io/blog/newsletter-2)+ Pyodide; relevant [marimo blog](https://marimo.io/blog/pyodide)) - will this be appreciated? Do let me know.
Also want to contribute to the docs usage for marimo here; like how it exists for jupyter (streamlit, gradio, etc.) - …
=> Add marimo example

.github/workflows/auto-ci.yml, pygwalker/data_parsers/database_parser.py, tests/test_data_parsers.py
related issue: https://github.com/Kanaries/pygwalker/issues/688
```python
from sqlalchemy import create_engine
from pygwalker.data_parsers.database_parser import Connector
connector = Connector(database_url, view_sql)
engine = create_engine(database_url)
connector = Connector.from_sqlalchemy_engine(engine, view_sql)
engine = create_engine(database_url)
with engine.connect() as conn:
connector = Connector.from_sqlalchemy_connection(conn, view_sql)
```
=> feat: add new init function for Connector

scripts/test-init.sh
I've incorporated the following changes:
1. Changed the shebang line to `#!/usr/bin/env bash` for maximum portability.
2. Added the `-s` option to curl to make it silent, consistent with the quiet `wget` command.
3. Introduced a variable filename to make the script more maintainable.
4. Added a check for available space in the target directory before downloading the file.
5. Implemented a trap to remove the partially downloaded file if the script exits due to an error.
=> Updated the bash script in test-init.sh

README.md, pygwalker/api/pygwalker.py
- allow exporting to svg with `export_chart_svg`
- support saving charts as svg
- document the new API
- `pytest -q` *(fails: command not found)*
=> Add programmatic export API
